global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-gateway'
    metrics_path: '/nginx_status'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:3001']
    scrape_interval: 15s

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-service:3002']
    scrape_interval: 15s

  - job_name: 'admin-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['admin-service:3003']
    scrape_interval: 15s

  - job_name: 'catalog-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['catalog-service:3003']
    scrape_interval: 10s

  - job_name: 'workout-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['workout-service:3004']
    scrape_interval: 15s

  - job_name: 'nutrition-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nutrition-service:3003']
    scrape_interval: 15s

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:3004']
    scrape_interval: 10s

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:3003']
    scrape_interval: 15s

  - job_name: 'partner-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['partner-service:3004']
    scrape_interval: 15s

  - job_name: 'delivery-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['delivery-service:3004']
    scrape_interval: 10s

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:3010']
    scrape_interval: 15s

  - job_name: 'recommendation-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['recommendation-service:3011']
    scrape_interval: 15s