global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway-service:3000']
    scrape_interval: 10s

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:3001']
    scrape_interval: 15s

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-service:3002']
    scrape_interval: 15s

  - job_name: 'admin-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['admin-service:3003']
    scrape_interval: 15s

  - job_name: 'catalog-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['catalog-service:3003']
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']